AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Parameters:
    MergeQueueName:
        Type: String
        Default: flowlogs-merge
        Description: Name of the SQS queue used to hold batches of files to be merged together (this is the queue that sits between the map and merge phases)
    RawQueueName:
        Type: String
        Default: flowlogs-raw
        Description: Name of the SQS queue that S3 has been configured to push object create events to (The map phase expects S3 object create events)

    MergeDLQQueueName:
        Type: String
        Default: flowlogs-merge-fail
        Description: Name of the SQS queue used to hold messages that failed to be completely processed by the merge process

    DebugLoggingEnabled: 
        Type: String
        Default: "true"
        Description: A flag indicating whether or not to write informational messaging to the std output (quite version, only enable when debugging issues)
        AllowedValues : 
          - "true"
          - "false"
    OutputBucket:
        Type: String
        Default: adams-got-data
        Description: The name of the S3 bucket to write the merged + compressed parquet files to
    OutputPath:
        Type: String
        Default: "output/"
        Description: "The path under which to write the merged + compressed parquet files to (merge phase will write hour specific parquet files in folders below this prefix, using the following format: /yyyy/MM/dd/HH/flowlogs-yyyy-MM-dd-HH-{uuid}.parquet)"
    TrackingTableName:
        Type: String
        Default: "flowlogs-tracking"     
        Description: "The name of the DynamoDB table to use for tracking which file(s) have been processed"
    AutoPartitioningEnabled: 
        Type: String
        Default: "true"
        Description: A flag indicating whether or not to add new partitions to an existing AWS Glue database table
        AllowedValues : 
          - "true"
          - "false"
    GlueDatabaseName:
        Type: String
        Default: "flowlogs"     
        Description: "The name of the database being used in the AWS Glue Catalogue."
    GlueTableName:
        Type: String
        Default: "data"     
        Description: "The name of the table witin the AWS Glue database to add partitions to."
    AthenaQueryOutputLocation:
        Type: String
        Default: ""
        Description: "The S3 location to write the ADD PARTITION query results to. If left blank, will default to a 'qresults' folder under the output path"

Globals:
  Function:
    Runtime: go1.x
    Handler: lambda-flowlogs-merger
    Environment:
      Variables:
        DEBUG_LOGGING: !Ref DebugLoggingEnabled
        MERGE_QUEUE_NAME: !Ref MergeQueueName
        MAP_QUEUE_NAME: !Ref RawQueueName
        OUTPUT_BUCKET: !Ref OutputBucket
        OUTPUT_PATH: !Ref OutputPath
        TRACKING_TABLE: !Ref TrackingTableName
        AUTO_PARTITIONING: !Ref AutoPartitioningEnabled
        GLUE_DATABASE_NAME: !Ref GlueDatabaseName
        GLUE_TABLE_NAME: !Ref GlueTableName
        ATHENA_RESULTS_LOC: !Ref AthenaQueryOutputLocation

Resources:
  FlowlogsMerger:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      FunctionName: flowlogs-merger
      Timeout: 900                      # Set to current max allowed timeout, the longer it is the less likely it is that we need to put some files back onto the SQS merge queue
      MemorySize: 3008
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonSQSFullAccess           # NB: This should refer to a policy that is more specific to the 2 SQS queues involved in this process
        - AmazonS3FullAccess            # NB: This should refer to a policy that is more specific to the S3 Bucket(s)/Prefix(es) used by this process
        - AmazonDynamoDBFullAccess      # NB: This should refer to a policy that is more specific to the DDB Table used by this process
        - AmazonAthenaFullAccess        # NB: This should refer to a policy that is more specific to the Athena DB/Table
      Events: 
        FlowlogsMergeQueueEvent:
          Type: SQS
          Properties:
            Queue: { "Fn::Sub": "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${MergeQueueName}" }
            BatchSize: 1
            Enabled: true
      DeadLetterQueue:
        Type: SQS
        TargetArn: { "Fn::Sub": "arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${MergeDLQQueueName}" }
      Environment:
        Variables:
          ACTION: "merge"
  FlowlogsMapper:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: bin/
        FunctionName: flowlogs-mapper
        Timeout: 900                    # 15 mintutes, function stops polling SQS 5mins before deadline, allowing 2 mins to complete any in-flight ops
        MemorySize: 512                 # Typically, function uses between 50 - 150MB, however, to cater for the case where events are coming in across the day at the same time, the function can push memory above 256MB due to storing message buffers for 1400 channels across the day.
        Policies:         
          - AWSLambdaBasicExecutionRole
          - AmazonSQSFullAccess         # NB: This should refer to a policy that is more specific to the 2 SQS queues involved in this process
          - AmazonS3FullAccess          # NB: This should refer to a policy that is more specific to the S3 Bucket(s)/Prefix(es) used by this process
        Events:
          RawFlowlogsMapperEvent:
            Type: Schedule
            Properties:
              Schedule: rate(10 minutes)
        Environment:
          Variables:
            ACTION: "map"
  FlowlogsTrackingTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName : !Ref TrackingTableName
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 200
        WriteCapacityUnits: 300
      TimeToLiveSpecification: 
        AttributeName: expiry
        Enabled: true
  FlowlogsRawQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref RawQueueName
      VisibilityTimeout: 920
  FlowlogsMergeQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref MergeQueueName
      VisibilityTimeout: 920
  FlowlogsMergeDLQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Ref MergeDLQQueueName
      VisibilityTimeout: 90
